"""Create the layout-matched Word copy from the official one-page CV PDF.

The separate ``*_editable.docx`` files are generated by the language-specific
builders. This script intentionally creates the public ``*_v4.docx`` files,
whose rendered page matches the PDF preview exactly.
"""

import sys
from pathlib import Path

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.shared import Inches, Pt


A4_WIDTH = Inches(8.2677)
A4_HEIGHT = Inches(11.6929)


def build(image_path: Path, output_path: Path) -> None:
    doc = Document()
    section = doc.sections[0]
    section.page_width = A4_WIDTH
    section.page_height = A4_HEIGHT
    section.top_margin = Inches(0)
    section.bottom_margin = Inches(0)
    section.left_margin = Inches(0)
    section.right_margin = Inches(0)
    section.header_distance = Inches(0)
    section.footer_distance = Inches(0)

    paragraph = doc.add_paragraph()
    paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER
    paragraph.paragraph_format.space_before = Pt(0)
    paragraph.paragraph_format.space_after = Pt(0)
    paragraph.paragraph_format.line_spacing = 1
    run = paragraph.add_run()
    picture = run.add_picture(str(image_path), width=A4_WIDTH, height=A4_HEIGHT)
    picture._inline.docPr.set("descr", "Rendered research CV page")

    doc.core_properties.title = output_path.stem.replace("_", " ")
    doc.core_properties.author = "Xuehao Xu"
    doc.save(output_path)


if __name__ == "__main__":
    if len(sys.argv) != 3:
        raise SystemExit("Usage: build_pdf_matched_cv_word.py INPUT.png OUTPUT.docx")
    build(Path(sys.argv[1]), Path(sys.argv[2]))
